# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pd.MBARTLarge50_pb2 as MBARTLarge50__pb2


class MBARTLarge50Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InterpretE2C = channel.unary_unary(
                '/MBARTLarge50/InterpretE2C',
                request_serializer=MBARTLarge50__pb2.EnglishRequest.SerializeToString,
                response_deserializer=MBARTLarge50__pb2.ChineseReply.FromString,
                )


class MBARTLarge50Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def InterpretE2C(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MBARTLarge50Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InterpretE2C': grpc.unary_unary_rpc_method_handler(
                    servicer.InterpretE2C,
                    request_deserializer=MBARTLarge50__pb2.EnglishRequest.FromString,
                    response_serializer=MBARTLarge50__pb2.ChineseReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MBARTLarge50', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MBARTLarge50(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InterpretE2C(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MBARTLarge50/InterpretE2C',
            MBARTLarge50__pb2.EnglishRequest.SerializeToString,
            MBARTLarge50__pb2.ChineseReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
