# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MBARTLarge50.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12MBARTLarge50.proto\"!\n\x0e\x45nglishRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x43hineseReply\x12\x0f\n\x07message\x18\x01 \x01(\t2@\n\x0cMBARTLarge50\x12\x30\n\x0cInterpretE2C\x12\x0f.EnglishRequest\x1a\r.ChineseReply\"\x00\x62\x06proto3')



_ENGLISHREQUEST = DESCRIPTOR.message_types_by_name['EnglishRequest']
_CHINESEREPLY = DESCRIPTOR.message_types_by_name['ChineseReply']
EnglishRequest = _reflection.GeneratedProtocolMessageType('EnglishRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENGLISHREQUEST,
  '__module__' : 'MBARTLarge50_pb2'
  # @@protoc_insertion_point(class_scope:EnglishRequest)
  })
_sym_db.RegisterMessage(EnglishRequest)

ChineseReply = _reflection.GeneratedProtocolMessageType('ChineseReply', (_message.Message,), {
  'DESCRIPTOR' : _CHINESEREPLY,
  '__module__' : 'MBARTLarge50_pb2'
  # @@protoc_insertion_point(class_scope:ChineseReply)
  })
_sym_db.RegisterMessage(ChineseReply)

_MBARTLARGE50 = DESCRIPTOR.services_by_name['MBARTLarge50']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENGLISHREQUEST._serialized_start=22
  _ENGLISHREQUEST._serialized_end=55
  _CHINESEREPLY._serialized_start=57
  _CHINESEREPLY._serialized_end=88
  _MBARTLARGE50._serialized_start=90
  _MBARTLARGE50._serialized_end=154
# @@protoc_insertion_point(module_scope)
